---
layout: cv
title: Tad Decker's Resume
---
# Tad Decker
Student in computer science, passionate developer, and eager learner.

<div id="webaddress">
<a href="https://linkedin.com/in/tad-decker-a615721b0">LinkedIn</a>
| <a href="mailto:tdecker234@gmail.com">tdecker234@gmail.com</a>
| <a href="https://github.com/trdecker">GitHub</a>
</div>

## Education

`2023–Pressent`
__Brigham Young University – Idaho__, Rexburg, ID

`2018–2023`
__Brigham Young University__, Provo, UT

## Related Experience

`2024–Present`
__Teaching Assistant, Brigham Young University–Idaho__, Provo, UT
- Developed a journaling mobile application in React Ionic, showcasing strong problem-solving skills and driven self-motivation
- Provided feedback in detailed reports, helping facilitate crucial decision making in creating a future class curriculum 
- Extensively documented my development process, adding an exhaustive report of the pros, cons, and unique attributes of React Ionic

`2022 - 2023`
__Full Stack Developer, Brigham Young University Office of IT__, Provo, UT
- Significantly contributed to the development of services for the BYU Honors Program, streamlining the application and thesis process.
- Successfully migrated major resources from legacy systems to modern services, reducing technical debt and enhancing security
- Worked with AWS products including EC2, Lambda, Fargate, and DynamoDB

## Service and Work History

`2021-2022`
__End-User Support, Brigham Young University__, Provo, UT

`2018-2020`
__Service Missionary__, Nashville Tennessee


<!-- ### Footer

Last updated: March 2024 -->